### PR TITLE
Code examples for episode 045 & 046

### PR DESCRIPTION
**Pull request by int3l**

### CODE REVIEW

**Comment by asottile** [comment]
oh interesting, I used overload way back then!

I'm thinking we should move these all into a `sample_code` directory as the repo homepage is getting a little difficult to navigate -- what do you think?

**Review by asottile — APPROVED** [review]

**Comment by int3l** [comment]
> oh interesting, I used overload way back then!
> 
> I'm thinking we should move these all into a `sample_code` directory as the repo homepage is getting a little difficult to navigate -- what do you think?

Well, this is why I suggested creating a subdir earlier. I can move them, no problem?

**Comment by asottile** [comment]
that would be great!  sorry I didn't listen to you earlier!

**Pull request merged**
