### PR TITLE
Code examples for episode 093 & 094

### PR DESCRIPTION
**Pull request by int3l**

### CODE REVIEW

**Comment by asottile** [comment]
@int3l was there a bug with github webhooks here? why the close-reopen? (just curious, I haven't had any reports of this being problematic for pre-commit.ci but I'm definitely interested in hearing if something went wrong here and then I can do some more investigation on it)

**Review by asottile — APPROVED** [review]

**Comment by int3l** [comment]
> @int3l was there a bug with github webhooks here? why the close-reopen? (just curious, I haven't had any reports of this being problematic for pre-commit.ci but I'm definitely interested in hearing if something went wrong here and then I can do some more investigation on it)

It was just me being silly -- I was running pre-commit (and the hooks) on python3.9 locally and the run was successful.
But of course, pre-commit.ci runs on python version < 3.9 -- which is why the run was failing.
And there was something weird with the UI when I force pushed -- there was no feedback for the current status.
Or maybe pre-commit.ci is just too fast -- I closed and reopen the PR, just to be sure that it was a real failing status (because I know from your videos that this will trigger a new run :P ).

**Comment by asottile** [comment]
ahh I see:

- https://results.pre-commit.ci/run/github/272297524/1610397125.dZh_1EmiSLSw6-7k5OeHGw
- https://results.pre-commit.ci/run/github/272297524/1610397282.BRtoaaV1Rcud31LkbA7UYw
- https://results.pre-commit.ci/run/github/272297524/1610397413.hh1sldOKSjOa5Mx8WBR7WA
- https://results.pre-commit.ci/run/github/272297524/1610397568.wKKp1WkmTsS2V-sF87JNDg

could probably use `language_version: python3.9` for example

**Comment by int3l** [comment]
Good idea, but It is already ignored in the flake8 config (I guess this is good for consistency and we already have this approach).
If you want I can try the language option, but I think that the current solution is ok. Or maybe you have something in mind about using future versions of python?

**Comment by asottile** [comment]
either way, doesn't really matter

**Pull request merged**
