### PR TITLE
Code examples for episode 251 & 252

### PR DESCRIPTION
**Pull request by int3l**

### CODE REVIEW

**Comment by int3l** [comment]
I wonder if I should include `py.typed` to all revisions for completeness.

**Comment by asottile** [comment]
> 
> 
> I wonder if I should include `py.typed` to all revisions for completeness.

probably a good idea

**Review by asottile — APPROVED** [review]

**Comment by int3l** [comment]
For the last revision (the stubs package), we don't need the `py.typed` (according to [PEP 561](https://www.python.org/dev/peps/pep-0561/))

**Pull request merged**
